### ISSUE TITLE
スマホで投稿記事のアイキャッチ画像の表示が崩れる

### ISSUE THREAD

**Issue by ecogrammer** [ito-artsfarm/itoartsfarm2016-static#4]
## 内容

表題の通りスマホで見ると投稿記事のアイキャッチ画像の表示が（縮小されず）崩れてしまいます。
以下の post.html が対象となりますが、そもそもアイキャッチ画像の表示を考慮していないため、WordPress側で無理くり実装したのが原因。

https://github.com/ito-artsfarm/itoartsfarm2016-static/blob/master/post.html

@keitakawamoto 

固定ページ合わせて、アイキャッチ画像を考慮した page.html post.html を作成していただきたいです..。作成後WPテーマに反映させます 🙇

**Comment by keitakawamoto** [comment]
@ecogrammer 了解です。少々お待ちください

**Comment by keitakawamoto** [comment]
これだけは済ませる！
@ecogrammer 

> WordPress側で無理くり実装したのが原因。

この部分のコードを見せてください

**Comment by keitakawamoto** [comment]
たぶん、アイキャッチが出力される部分にアイキャッチ用セレクタを設定し、 `max-width` を設定すればそれで済む。

![image](https://cloud.githubusercontent.com/assets/1661325/18040986/97749290-6dee-11e6-9f62-06bc01633b10.png)

あと日付のあとにしたいということ、マージンが取れておらず読みにくくなってしまっていることも解消したい。

**Comment by keitakawamoto** [comment]
@ecogrammer 

> 固定ページ合わせて、アイキャッチ画像を考慮した page.html post.html を作成していただきたいです..。作成後WPテーマに反映させます 🙇

アイキャッチ画像の出力に関してはそもそも `itoartsfarm2016-static` に含まれていないので、こっちのリポジトリでは難しいです。
なので、以下の手順を行ってください。
- https://github.com/ito-artsfarm/itoartsfarm2016-wp/blob/master/content.php#L18
  - 閉じタグを `</h2>`に変更
- https://github.com/ito-artsfarm/itoartsfarm2016-wp/blob/master/content.php#L23-L27
  - このへんをL36あたり（日付・タグなどのあと）に移動
- アイキャッチ部分のimg要素から `width="800" height="315"` という指定外す（ぶち抜かないためにCSSで制御する）
- アイキャッチ部分のimg要素に `class="eyecatch"` を取り付ける

```
.eyecatch  {
    max-width: 100%;
    margin-bottom: 30px;
}
```

すると、このようになります。試してみてください。

![image](https://cloud.githubusercontent.com/assets/1661325/18041180/c86ee3d0-6df0-11e6-8335-0f905776befc.png)

**Comment by ecogrammer** [comment]
@keitakawamoto 

`</h1>`  。。。残念すぎますね。直します。
他、対応方法をもとに改修します！

仕事終わってから！

**Comment by makizonokenji** [comment]
@ecogrammer @keitakawamoto @shoyan 
お仕事でお忙しいところすみません！ありがとうございます！！

**Comment by ecogrammer** [comment]
対応しました。
